Repository numberOnethemepark/themepark, pull requests merged in 2025-04, with the labels that each got.

#13 ⚙ setting [env] eureka server 및 root 모듈 세팅
  .gitignore
  build.gradle
  eureka-server/build.gradle
  eureka-server/gradle/wrapper/gradle-wrapper.properties
  eureka-server/src/main/java/com/business/eurekaserver/EurekaServerApplication.java
  eureka-server/src/main/resources/application.yml
  eureka-server/src/test/java/com/business/eurekaserver/EurekaServerApplicationTests.java
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: ✨ feat, ⚙ setting

#14 ✨ feat [#8-themepark] 테마파크 서비스 추가
  settings.gradle
  themepark-service/build.gradle
  themepark-service/gradle/wrapper/gradle-wrapper.properties
  themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java
  themepark-service/src/main/resources/application.yml
  themepark-service/src/test/java/com/business/themeparkservice/ThemeparkServiceApplicationTests.java
Labels: ✨ feat, ⚙ setting

#15 ✨ feat [#8-themepark] 테마파크 서비스 추가
  themepark-service/build.gradle
Labels: ✨ feat, ⚙ setting

#16 ✨ feat | 주문 서비스 추가
  build.gradle
  order-service/build.gradle
  order-service/gradle/wrapper/gradle-wrapper.properties
  order-service/src/main/java/com/sparta/orderservice/OrderServiceApplication.java
  order-service/src/main/resources/application.yml
  order-service/src/test/java/com/sparta/orderservice/OrderServiceApplicationTests.java
  settings.gradle
Labels: ✨ feat, ⚙ setting

#18 ✨ feat [#10-product] 상품 서비스 추가
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/ProductServiceApplication.java
  product-service/src/main/resources/application.yml
  settings.gradle
Labels: ✨ feat, ⚙ setting

#19 ✨ feat [#9-gateway] gateway 생성
  gateway-service/build.gradle
  gateway-service/gradle/wrapper/gradle-wrapper.properties
  gateway-service/src/main/java/com/business/gatewayservice/GatewayServiceApplication.java
  gateway-service/src/main/resources/application.yml
  gateway-service/src/test/java/com/business/gatewayservice/GatewayServiceApplicationTests.java
  settings.gradle
Labels: ✨ feat, ⚙ setting

#20 ✨ feat [#17-user] user 서비스 생성
  settings.gradle
  user-service/build.gradle
  user-service/gradle/wrapper/gradle-wrapper.properties
  user-service/src/main/java/com/business/userservice/UserServiceApplication.java
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/business/userservice/UserServiceApplicationTests.java
Labels: ✨ feat, ⚙ setting

#24 ⚙ setting [#10-product] gradle-wrapper.properties 추가
  product-service/gradle/wrapper/gradle-wrapper.properties
Labels: ✏️ fix

#27 ✨ feat [#26-product] product controller, dto 구현
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductPostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/common/dto/ResDTO.java
  product-service/src/main/java/com/business/productservice/domain/product/entity/ProductEntity.java
  product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
  product-service/src/main/java/com/business/productservice/domain/product/vo/ProductType.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/java/com/business/productservice/ProductServiceApplicationTests.java
Labels: ✨ feat

#28 ✨ feat [#21-themepark] 테마파크 Create 구현
  build.gradle
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPostDTOApiv1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/vo/ThemeparkType.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✨ feat

#29 ✨ feat [#25-user-join] 회원가입 controller, dto 구현
  gateway-service/src/main/resources/application.yml
  user-service/build.gradle
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthJoinDTOApiV1.java
  user-service/src/main/java/com/business/userservice/common/dto/ResDTO.java
  user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
Labels: ✨ feat

#30 ✨ feat [#21-themepark-read] 테마파크 Read 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetByIdDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/common/dto/ResDTO.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✨ feat

#32 ✨ feat [#25-user-login] 로그인 controller, dto 구현
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostGuestLoginDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostJoinDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostLoginDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthPostGuestLoginDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthPostLoginDTOApiV1.java
  user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
Labels: ✨ feat

#33 ✨ feat [#31-order-create] 주문 create 기능 구현
  build.gradle
  order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrdersPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResDto.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java
Labels: ✨ feat

#35 ✨ feat [#26-product] 상품 Read controller, dto 구현
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/business/productservice/domain/product/vo/ProductStatus.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
Labels: ✨ feat

#36 ✨ feat[#21-themepark-delete] 테마파크 Delete 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✨ feat

#37 ✨ feat [#31 order update] 주문 update 기능 구현
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrderPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrdersPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java
Labels: ✨ feat

#38 ✨ feat [#25-user-update] 회원 정보 수정 controller, dto 구현
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPutDTOApiV1.java
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
Labels: ✨ feat

#40 ✨ feat [#31-order-read] 주문 read 기능 구현
  build.gradle
  order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrdersPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResOrderGetDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java
Labels: ✨ feat, ✏️ fix

#41 ✨ feat [#26-product-update] 상품 수정 controller, dto 구현
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPutDTOApiV1.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
Labels: ✨ feat

#42 ✨ feat [#22-hashtag-read] 해시태그 Read 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagGetByIdDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
Labels: ✨ feat

#43 ✨ feat [#31-order-delete] 주문 delete 기능 구현
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java
Labels: ✨ feat

#44 ✨ feat [#22-hashtag-update] 해시태그 Update 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/request/ReqHashtagPutDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagPutDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
Labels: ✨ feat

#45 ✨ feat [#26-product-delete] 상품 삭제 controller 구현
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
Labels: ✨ feat

#46 ✨ feat [#22-hashtag-delete] 해시태그 Delete 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
Labels: ✨ feat

#48 ✨ feat [#25-user-read] 회원 정보 조회 controller, dto 구현
  user-service/build.gradle
  user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetByIdDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetDTOApiV1.java
  user-service/src/main/java/com/business/userservice/domain/user/entity/UserEntity.java
  user-service/src/main/java/com/business/userservice/domain/user/vo/RoleType.java
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
Labels: ✨ feat

#49 ✨ feat [#22-waiting-create] 테마파크대기 Create 기능 구현
  gateway-service/src/main/resources/application.yml
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/request/ReqWaitingPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/common/dto/ResDTO.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/vo/WaitingStatus.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: ✨ feat

#51 ✨ feat [#47-product-stock-update] 상품 재고 복구, 차감 controller 및 dto 구현
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockDecreasePatchDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockRestorePatchDTOApiV1.java
  product-service/src/main/java/com/business/productservice/presentation/controller/StockControllerApiV1.java
Labels: ✨ feat

#52 ✨ feat [#25-user-restriction] 회원 탈퇴, 블랙리스트 설정 controller, dto 구현
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserDeleteDTOApiV1.java
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
Labels: ✨ feat

#54 ✨ feat [#22-waiting-done] 테마파크 대기완료 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDoneDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: ✨ feat

#56 ✨ feat [#53-payment-update] 결제 update 기능 구현
  order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqPaymentPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqPaymentPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1.java
Labels: ✨ feat

#61 ✨ feat [#22-waiting-delete] 테마파크대기 Delete 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: ✨ feat

#60 ⚙ setting [#59-gateway-swagger] Swagger 설정
  gateway-service/build.gradle
  gateway-service/src/main/resources/application.yml
  user-service/build.gradle
Labels: ⚙ setting

#62 ✨ feat [#26-product-read] 상품 전체 조회 및 검색 controller, dto 구현
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPutDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetDTOApiV1.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
Labels: ✨ feat

#63 ✨ feat [#/31-order-get-userId] 주문 get by userid 기능 구현
  order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResOrdersGetByIdDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java
Labels: ✨ feat

#64 ✨ feat[#21-themepark-search] 테마파크 Search 기능 구현
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✨ feat

#67 🔨 refactor [#66-user] User 관련 Controller, DTO 피드백 적용
  user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetByIdDTOApiV1.java
  user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
Labels: 🔨 refactor

#68 ✨ feat [#23-waiting-search] 테마파크대기열 Search 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: ✨ feat

#70 ✏️ fix [#69-themepark-fix] 테마파크 컨트롤러 네이밍 수정
  .github/PULL_REQUEST_TEMPLATE.md
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
Labels: ✏️ fix

#72 🎈 test [#69-themepark] 테마파크 테스트코드 작성
  build.gradle
  themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
Labels: 🎈 test

#75 🔨 refactor [#26-product] 상품 controller, dto 리팩토링
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockDecreasePatchDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockRestorePatchDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductPostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/main/java/com/business/productservice/presentation/controller/StockControllerApiV1.java
  product-service/src/main/resources/application-dev.yml
  product-service/src/main/resources/application.yml
Labels: 🔨 refactor

#77 🎈 test [#73-user] 회원 관련 테스트 코드 작성
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostJoinDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostLoginDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPutDTOApiV1.java
  user-service/src/main/resources/application-dev.yml
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
  user-service/src/test/java/com/business/userservice/user/presentation/controller/UserControllerApiV1Test.java
Labels: 🎈 test

#79 🔨 refactor[#78-themepark] 테마파크 코드 리팩토링
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPutDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetByIdDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPostDTOApiv1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPutDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/main/resources/application-dev.yml
  themepark-service/src/main/resources/application-prod.yml
  themepark-service/src/main/resources/application.yml
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: 🔨 refactor

#80 🎈 test [#71-themepark] 테마파크 테스트코드 작성
  themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
Labels: 🎈 test

#81 🎈 test [#71-themepark] 테마파크 해시태그 테스트코드 작성
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1Test.java
Labels: 🎈 test

#83 🔨 refactor, ✏️ fix, 🎈 test [/#74 order test] 주문 test 코드 작성
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrderPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/request/ReqOrdersPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResOrderGetDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/response/ResOrdersGetByIdDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-prod.yml
  order-service/src/main/resources/application.yml
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1Test.java
Labels: 🔨 refactor, 🎈 test

#86 🎈 test [#71-themepark-waiting] 테마파크 대기열 테스트코드 작성
  themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1Test.java
Labels: 🎈 test

#87 🎈 test [#76-product-stock] 상품 테스트 코드 작성
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockDecreasePostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockRestorePostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
Labels: 🎈 test

#91 📄 docs[#89-themepark] 테마파크 swagger 자동 문서화기능 추가
  themepark-service/build.gradle
  themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1Test.java
Labels: 📄 docs, ⚙ setting

#92 ⚙ setting [#90-gateway-swagger] Swagger 문서 통합 설정
  gateway-service/src/main/resources/application.yml
Labels: ⚙ setting

#93 ⚙ setting [ /#74-order-swagger] 테스트 코드 스웨거 문서화
  order-service/build.gradle
  order-service/src/main/resources/application-dev.yml
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1Test.java
Labels: ⚙ setting

#94 📄 docs [#89-themepark] 테마파크 swagger 자동 문서화기능 일부수정
  themepark-service/build.gradle
Labels: 📄 docs

#95 📄 docs [#88-product] 상품 서비스 API RestDocs 문서화 및 스웨거 자동화 적용
  product-service/build.gradle
  product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
Labels: 📄 docs

#96 ✏️ fix [/#74-test-swagger] 파일 오류 수정
  order-service/src/main/resources/application-dev.yml
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1Test.java
Labels: 📄 docs, ✏️ fix

#98 ⚙ setting [#97 user swagger] 테스트 코드와 Swagger 연동
  user-service/build.gradle
  user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
  user-service/src/test/java/com/business/userservice/user/presentation/controller/UserControllerApiV1Test.java
Labels: ⚙ setting

#99 ⚙ setting[common-setting] 레포지토리 연결설정
  build.gradle
  settings.gradle
  themepark-service/build.gradle
Labels: ⚙ setting

#102 ✨ feat [#100 themepark] 테마파크 entity,repository 추가
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/repository/ThemeparkRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/infastructure/ThemeparkJpaRepository.java
  themepark-service/src/main/resources/application-dev.yml
Labels: ✨ feat, ⚙ setting

#103 ✨ feat [#100-themepark] 테마파크 해시태그 entity,repository 추가
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/repository/HashtagRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/infastructure/persistence/hashtag/HashtagJpaRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/infastructure/persistence/themepark/ThemeparkJpaRepository.java
Labels: ✨ feat

#105 ⚙ setting [#104-product] 상품 엔티티 생성, 의존성 추가, db 설정
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/domain/product/entity/ProductEntity.java
  product-service/src/main/resources/application-dev.yml
Labels: ✨ feat, ⚙ setting

#107 ✨ feat[#100-themepark] 테마파크 대기열 entity,repository 추가
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/persistence/waiting/WaitingJpaRepository.java
Labels: ✨ feat, ⚙ setting

#110 🔨 refactor [#109-gateway-eureka-user] build.gradle 설정
  eureka-server/build.gradle
  gateway-service/build.gradle
  user-service/build.gradle
Labels: ⚙ setting, 🔨 refactor

#111 ✨ feat [#108-themepark-create] 테마파크 생성 api
  themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java
  themepark-service/src/main/java/com/business/themeparkservice/config/AuditorAwareConfig.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/common/dto/ResDTO.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/infastructure/persistence/hashtag/HashtagJpaRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPostDTOApiv1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/common/dto/ResDTO.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkHashtagEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/repository/ThemeparkHashtagRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/infastructure/persistence/themepark/ThemeparkHashtagJpaRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/common/dto/ResDTO.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/main/resources/application-dev.yml
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✨ feat

#113 ✨ feat [Feat/#101 order entity] order,payment 엔티티, 레파지토리 추가 , build.garadle 변경
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/request/ReqOrderPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/request/ReqOrdersPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/response/ResDto.java
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/response/ResOrderGetDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/response/ResOrdersGetByIdDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/entity/Order.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/repository/OrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/dto/request/ReqPaymentPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/dto/request/ReqPaymentPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/dto/response/ResPaymentGetDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/domain/entity/Payment.java
  order-service/src/main/java/com/sparta/orderservice/payment/domain/repository/PaymentRepository.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/controller/PaymentControllerApiV1.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1Test.java
Labels: ✨ feat

#117 ✨ feat[#112-hashtag-create] 테마파크해시태그 생성 api 구현
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/request/ReqHashtagPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPostDTOApiv1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
  themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
  themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1Test.java
Labels: ✨ feat

#116 ✨ feat [#114-user-join] 회원가입 기능 구현
  user-service/build.gradle
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostJoinDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthPostJoinDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/AuthServiceApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/AuthServiceImplApiV1.java
  user-service/src/main/java/com/business/userservice/common/dto/ResDTO.java
  user-service/src/main/java/com/business/userservice/domain/user/entity/UserEntity.java
  user-service/src/main/java/com/business/userservice/domain/user/repository/UserRepository.java
  user-service/src/main/java/com/business/userservice/domain/user/vo/RoleType.java
  user-service/src/main/java/com/business/userservice/infrastructure/persistence/user/UserJpaRepository.java
  user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
Labels: ✨ feat

#121 ✨ feat [#106-product-create] 상품 생성 api 구현
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/ProductServiceApplication.java
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPutDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqStockRestorePostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductPostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/common/dto/ResDTO.java
  product-service/src/main/java/com/business/productservice/config/AuditorAwareConfig.java
  product-service/src/main/java/com/business/productservice/domain/product/entity/ProductEntity.java
  product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
  product-service/src/main/java/com/business/productservice/domain/product/repository/ProductRepository.java
  product-service/src/main/java/com/business/productservice/infrastructure/persistence/product/ProductJpaRepository.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/main/resources/application-dev.yml
  product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
  product-service/src/test/resources/httpclient/product.http
Labels: ✨ feat, ✏️ fix

#125 ✨ feat[#124 hashtag update] 해시태그 수정기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagGetByIdDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagPutDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
Labels: ✨ feat

#123 ✨ feat[#119-hashtag-read] 해시태그 조회 기능 구현(단건)
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
Labels: ✨ feat

#126 ✨ feat [#120-user-login] 로그인 기능 구현
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostLoginDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthPostLoginDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserDetailsServiceImpl.java
  user-service/src/main/java/com/business/userservice/domain/user/entity/UserEntity.java
  user-service/src/main/java/com/business/userservice/infrastructure/auth/JwtFilter.java
  user-service/src/main/java/com/business/userservice/infrastructure/auth/JwtUtil.java
  user-service/src/main/java/com/business/userservice/infrastructure/auth/LoginFilter.java
  user-service/src/main/java/com/business/userservice/infrastructure/auth/UserDetailsImpl.java
  user-service/src/main/java/com/business/userservice/infrastructure/config/SecurityConfig.java
  user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
  user-service/src/main/resources/application-dev.yml
Labels: ✨ feat

#127 ✨ feat [#119-hashtag-search] 해시태그 검색 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/dto/response/ResHashtagGetDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/repository/HashtagRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/infastructure/persistence/hashtag/HashtagJpaRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/ThemeparkServiceApplicationTests.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
Labels: ✨ feat

#129 ✨ feat [#118-themepark-read] 테마파크 단건조회 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetByIdDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkHashtagEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/repository/ThemeparkHashtagRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✨ feat

#131 ✨ feat [#122-product-read] 상품 단건 조회 기능 구현
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/exception/ProductExceptionCode.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
  product-service/src/test/resources/httpclient/product.http
Labels: ✨ feat

#133 ✨ feat[#118-themepark-search] 테마파크 검색 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkGetDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/repository/ThemeparkRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/infastructure/persistence/themepark/ThemeparkJpaRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✨ feat

#137 ✨ feat [#128-hashtag-delete] 해시태그 삭제 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/domain/entity/HashtagEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
Labels: ✨ feat

#135 ✨ feat [#115-order-create] 주문 create 기능 구현
  order-service/src/main/java/com/sparta/orderservice/order/application/client/PaymentServiceClient.java
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/request/ReqPaymentPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/response/ResDto.java
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/response/ResPaymentPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/facade/OrderFacade.java
  order-service/src/main/java/com/sparta/orderservice/order/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/order/application/usecase/OrderUseCase.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/entity/Order.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/repository/OrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/order/infrastructure/repository/JpaOrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/order/infrastructure/repository/SpringDataJpaOrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/request/ReqOrderPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/request/ReqOrdersPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/response/ResOrderGetDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/response/ResOrdersGetByIdDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/infrastructure/repository/PaymentRepository.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/controller/PaymentControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/dto/request/ReqPaymentPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/dto/request/ReqPaymentPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/dto/response/ResPaymentGetDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/dto/response/ResPaymentPostDtoApiV1.java
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1Test.java
Labels: ✨ feat

#138 ✨ feat [#130-user-read] 회원 정보 조회 구현
  user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetByIdDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/response/ResUserGetDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserServiceApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
  user-service/src/main/java/com/business/userservice/domain/user/repository/UserRepository.java
  user-service/src/main/java/com/business/userservice/infrastructure/persistence/user/UserJpaRepository.java
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
Labels: ✨ feat

#139 ✨ feat [#132-product-update] 상품 정보 수정 기능 구현
  product-service/src/main/java/com/business/productservice/application/dto/request/ReqProductPutDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductPutDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/domain/product/entity/ProductEntity.java
  product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
  product-service/src/test/resources/httpclient/product.http
Labels: ✨ feat

#143 ✨ feat [#140-product-delete] 상품 삭제 기능 구현 및 예외 발생 시 빈 등록 문제 개선
  product-service/src/main/java/com/business/productservice/ProductServiceApplication.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/domain/product/repository/StockRepository.java
  product-service/src/main/java/com/business/productservice/infrastructure/persistence/product/StockJpaRepository.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/resources/httpclient/product.http
Labels: 🐛 bug, ✨ feat

#146 ✨ feat [#134-themepark-update] 테마파크 수정 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/response/ResThemeparkPutDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✨ feat

#148 ✨ feat[#145-waiting-create] 대기열 생성 기능 구현
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/request/ReqWaitingPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/persistence/waiting/WaitingJpaRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: ✨ feat

#151 ✨ feat [#149-user-update-delete] 회원 탈퇴 및 회원 정보 수정 구현
  user-service/build.gradle
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserDeleteDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPutDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserServiceApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
  user-service/src/main/java/com/business/userservice/domain/user/entity/UserEntity.java
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
Labels: ✨ feat

#153 ✨ feat [#142-product-search] 상품 다중 검색 기능 구현
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/application/dto/response/ResProductGetDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/domain/product/repository/ProductRepository.java
  product-service/src/main/java/com/business/productservice/infrastructure/persistence/product/ProductJpaRepository.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/resources/httpclient/product.http
Labels: ✨ feat

#152 ✨ feat [#147-themepark-delete] 테마파크 삭제 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/entity/ThemeparkEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/domain/repository/ThemeparkHashtagRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✨ feat

#154 ✨ feat[#150-waiting-read] 대기 단건조회 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetByIdDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/persistence/waiting/WaitingJpaRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: ✨ feat

#156 ✨ feat [#144-product-stock-decrease] 상품-재고 차감 기능 구현
  product-service/src/main/java/com/business/productservice/application/exception/ProductExceptionCode.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
  product-service/src/main/java/com/business/productservice/domain/product/repository/StockRepository.java
  product-service/src/main/java/com/business/productservice/domain/product/repository/StockRepositoryImpl.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/resources/httpclient/product.http
Labels: ✨ feat

#157 ✨ feat[#155-waiting-done] 대기 완료 기능 구현
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDoneDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: ✨ feat

#160 ✨ feat[#159-waiting-delete] 대기 삭제 기능 구현
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: ✨ feat

#164 ✨ feat [#163-docker-compose] 데이터베이스 docker 연결
  docker-compose.yml
  init.sql
  themepark-service/src/main/resources/application-dev.yml
Labels: ✨ feat

#166 🔨 refactor[#165-themepark-error] 테마파크 에러리턴코드 리팩토링
  themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/exception/HashtagExceptionCode.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/application/service/HashtagServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/exception/ThemeparkExceptionCode.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/exception/WaitingExceptionCode.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
Labels: 🔨 refactor

#170 ✨ feat [#169-gateway-jwt] JWT 인증 및 인가 필터 추가
  gateway-service/build.gradle
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/SecurityConfig.java
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
  gateway-service/src/main/resources/application.yml
Labels: ✨ feat

#172 🔨 refactor [#171-user-exception] CustomException 적용
  user-service/src/main/java/com/business/userservice/UserServiceApplication.java
  user-service/src/main/java/com/business/userservice/application/exception/AuthExceptionCode.java
  user-service/src/main/java/com/business/userservice/application/exception/UserExceptionCode.java
  user-service/src/main/java/com/business/userservice/application/service/AuthServiceImplApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
  user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtAuthenticationFilter.java
  user-service/src/main/java/com/business/userservice/infrastructure/security/UserDetailsServiceImpl.java
Labels: 🔨 refactor

#173 ✨ feat [#144-product-restore] 재고 복구 기능 구현
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
  product-service/src/main/java/com/business/productservice/domain/product/repository/StockRepositoryImpl.java
  product-service/src/main/java/com/business/productservice/infrastructure/persistence/product/StockJpaRepository.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/main/resources/application-dev.yml
  product-service/src/test/resources/httpclient/product.http
Labels: ✨ feat

#175 ✨ feat [/#136 payment create] 주문객체생성 -> 결제 -> 결제객체생성 기능 구현
  build.gradle
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/OrderServiceApplication.java
  order-service/src/main/java/com/sparta/orderservice/order/application/client/PaymentServiceClient.java
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/request/ReqPaymentPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/response/ResPaymentPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/facade/OrderFacade.java
  order-service/src/main/java/com/sparta/orderservice/order/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/order/application/usecase/OrderUseCase.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/entity/OrderEntity.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/repository/OrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/order/infrastructure/repository/JpaOrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/order/infrastructure/repository/SpringDataJpaOrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/request/ReqOrdersPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/response/ResOrderPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/dto/request/ReqPaymentTossDto.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/dto/response/ResPaymentTossDto.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/facade/PaymentFacade.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/service/PaymentService.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/usercase/PaymentUseCase.java
  order-service/src/main/java/com/sparta/orderservice/payment/domain/entity/Payment.java
  order-service/src/main/java/com/sparta/orderservice/payment/domain/repository/PaymentRepository.java
  order-service/src/main/java/com/sparta/orderservice/payment/infrastructure/client/TossPaymentsClient.java
  order-service/src/main/java/com/sparta/orderservice/payment/infrastructure/config/TossFeignConfig.java
  order-service/src/main/java/com/sparta/orderservice/payment/infrastructure/repository/JpaPaymentRepository.java
  order-service/src/main/java/com/sparta/orderservice/payment/infrastructure/repository/SpringDataJpaPaymentRepository.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/controller/PaymentControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/dto/request/ReqPaymentPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/dto/request/ReqPaymentPutDtoApiV1.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/static/fail.html
  order-service/src/main/resources/static/orders.html
  order-service/src/main/resources/static/payments.html
  order-service/src/main/resources/static/paysuccess.html
  order-service/src/main/resources/static/success.html
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1Test.java
Labels: ✨ feat, ⚙ setting, 🔨 refactor, 🗑️ remove

#180 🔨 refactor [#177-gateway-exception] CustomException 적용
  gateway-service/build.gradle
  gateway-service/src/main/java/com/business/gatewayservice/application/exception/GatewayExceptionCode.java
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
Labels: 🔨 refactor

#183 ✨ feat [#182-user-role] User API에 권한 설정
  user-service/build.gradle
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
Labels: ✨ feat

#184 ✨ feat [#178 order update] 주문 update 기능 구현
  order-service/src/main/java/com/sparta/orderservice/order/application/facade/OrderFacade.java
  order-service/src/main/java/com/sparta/orderservice/order/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/order/application/usecase/OrderUseCase.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/entity/OrderEntity.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/repository/OrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/order/infrastructure/repository/JpaOrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/request/ReqOrderPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/service/PaymentService.java
  order-service/src/main/java/com/sparta/orderservice/payment/infrastructure/feign/TossPaymentsClient.java
Labels: ✨ feat, ✏️ fix

#189 🎈 test [#188-user] User 관련 테스트 코드 수정
  gateway-service/build.gradle
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
  user-service/build.gradle
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqAuthPostLoginDTOApiV1.java
  user-service/src/test/java/com/business/userservice/httpClient/auth.http
  user-service/src/test/java/com/business/userservice/httpClient/user.http
  user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
Labels: 🎈 test

#194 🔨 refactor[#187-themepark] 테마파크 코드 리팩토링
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java
  themepark-service/src/main/java/com/business/themeparkservice/config/AuditorAwareConfig.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/service/ThemeparkServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
  themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
Labels: 🔨 refactor

#197 ✨ feat [#161-product-stock-read] 상품 재고 조회 api 추가
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/ProductServiceApplication.java
  product-service/src/main/java/com/business/productservice/application/dto/response/ResStockGetByIdDTOApiv1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/config/AuditorAwareConfig.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/resources/httpclient/product.http
Labels: ✨ feat

#198 🔨 refactor [#190-user] 회원 역할 이름 수정, refresh 응답 dto, test 생성
  user-service/build.gradle
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPostDeleteDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthGetRefreshDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserServiceApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
  user-service/src/main/java/com/business/userservice/domain/user/vo/RoleType.java
  user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
  user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
  user-service/src/test/java/com/business/userservice/user/presentation/controller/UserControllerApiV1Test.java
Labels: 🔨 refactor, 🎈 test

#203 🔨 refactor [#201 order refactory] Order/Payment 도메인 리펙토링
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/order/application/facade/OrderFacade.java
  order-service/src/main/java/com/sparta/orderservice/order/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/order/application/usecase/OrderUseCase.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/entity/OrderEntity.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/vo/paymentStatus.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/request/ReqOrderPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/response/ResOrderGetDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/response/ResOrdersGetByIdDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/facade/PaymentFacade.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/service/PaymentService.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/usercase/PaymentUseCase.java
  order-service/src/main/java/com/sparta/orderservice/payment/domain/entity/PaymentEntity.java
  order-service/src/main/java/com/sparta/orderservice/payment/domain/repository/PaymentRepository.java
  order-service/src/main/java/com/sparta/orderservice/payment/domain/vo/PaymentStatus.java
  order-service/src/main/java/com/sparta/orderservice/payment/infrastructure/repository/JpaPaymentRepository.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/controller/PaymentControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/dto/response/ResPaymentGetDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/payment/presentation/dto/response/ResPaymentPostDtoApiV1.java
Labels: 🔨 refactor

#204 🔨 refactor[#187-themepark] 테마파크 대기열 코드 리팩토링
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/request/ReqWaitingPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetByIdDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingGetDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostCancelDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/response/ResWaitingPostDoneDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
  themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1Test.java
Labels: 🔨 refactor

#207 🔨 refactor[#187-themepark-test] 테마파크 테스트 코드 리팩토링
  themepark-service/build.gradle
  themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
  themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1Test.java
Labels: 🔨 refactor

#208 🔨 refactor [Refactor/#201 order refactory]
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/SecurityConfig.java
  order-service/src/main/resources/static/orders.html
Labels: 🔨 refactor

#209 ✏️ fix [/#201 order refactory] yml 파일 수정
  order-service/src/main/resources/application-dev.yml
Labels: ✏️ fix

#211 🔨 refactor[#210-waiting] 대기열 코드 리팩토링
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/exception/WaitingExceptionCode.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: 🔨 refactor

#212 ✨ feat [#196-product-auth] 상품 서비스 권한 추가
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
  product-service/src/test/resources/httpclient/product.http
Labels: ✨ feat

#215 🔨 refactor [#214-gateway-jwt] jwt 필터에 HTTP 메소드별 경로 제외 설정 추가
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
Labels: 🔨 refactor

#217 ✨ feat [#216-slack] 슬랙 Entity 및 Repository 생성
  gateway-service/src/main/resources/application.yml
  init.sql
  settings.gradle
  slack-service/build.gradle
  slack-service/gradle/wrapper/gradle-wrapper.properties
  slack-service/src/main/java/com/business/slackservice/SlackServiceApplication.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/entity/SlackEntity.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/entity/SlackEventTypeEntity.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/entity/SlackTarget.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/entity/SlackTemplateEntity.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/repository/SlackEventTypeRepository.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/repository/SlackRepository.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/repository/SlackTemplateRepository.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/vo/SlackStatus.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/vo/TargetType.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackEventTypeJpaRepository.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackJpaRepository.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackTemplateJpaRepository.java
  slack-service/src/main/resources/application-dev.yml
  slack-service/src/main/resources/application.yml
  slack-service/src/test/java/com/business/slackservice/SlackServiceApplicationTests.java
Labels: ✨ feat

#219 ✨ feat [#218-slack-event-type] 슬랙 이벤트 타입 CRUD 구현
  slack-service/src/main/java/com/business/slackservice/SlackServiceApplication.java
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePostDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePutDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypeGetByIdDTOV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypeGetDTOV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypePostDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/exception/SlackExceptionCode.java
  slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeServiceApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeServiceImplApiV1.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/entity/SlackEventTypeEntity.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/repository/SlackEventTypeRepository.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackEventTypeJpaRepository.java
  slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackEventTypeControllerV1.java
Labels: ✨ feat

#221 🔨 refactor [#220-slack] 패키지 구조 변경 및 파일 이동
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePostDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePutDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypeGetByIdDTOV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypeGetDTOV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/response/slackEventType/ResSlackEventTypePostDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeService.java
  slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeServiceImplApiV1.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/entity/SlackEntity.java
  slack-service/src/main/java/com/business/slackservice/domain/slack/repository/SlackTemplateRepository.java
  slack-service/src/main/java/com/business/slackservice/domain/slackEventType/entity/SlackEventTypeEntity.java
  slack-service/src/main/java/com/business/slackservice/domain/slackEventType/repository/SlackEventTypeRepository.java
  slack-service/src/main/java/com/business/slackservice/domain/slackTemplate/entity/SlackTemplateEntity.java
  slack-service/src/main/java/com/business/slackservice/domain/slackTemplate/repository/SlackTemplateRepository.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackEventTypeJpaRepository.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackTemplateJpaRepository.java
  slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackEventTypeControllerV1.java
Labels: 🔨 refactor

#227 ✏️ fix [#213-product] 재고차감/복구 조건문 추가
  product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
Labels: 🔨 refactor

#230 🎈 test [#229-slack] slack 관련 crud http test 생성
  slack-service/src/test/java/com/business/slackservice/httpClient/slack.http
Labels: 🎈 test

#232 🎈 test [#231 slack] SlackEventType Controller 테스트 코드 작성
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePostDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slackEventType/ReqSlackEventTypePutDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackEventTypeControllerApiV1.java
  slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackEventTypeControllerApiV1Test.java
Labels: 🎈 test

#234 ✨ feat [#233 user] jwt에 slackId 추가
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
  user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtAuthenticationFilter.java
  user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtUtil.java
  user-service/src/main/java/com/business/userservice/infrastructure/security/UserDetailsImpl.java
  user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
Labels: ✨ feat

#236 🔨 refactor [#235 slack] EventType Id 조회에서 Name 조회로 변경
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slack/ReqSlackPostDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/service/SlackEventTypeService.java
  slack-service/src/main/java/com/business/slackservice/application/service/SlackServiceImplApiV1.java
  slack-service/src/main/java/com/business/slackservice/domain/slackEventType/repository/SlackEventTypeRepository.java
  slack-service/src/test/java/com/business/slackservice/httpClient/slack.http
Labels: 🔨 refactor

#237 ✨ feat [#223-waiting] 대기열 feignclient 생성
  .gitignore
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/SecurityConfig.java
  slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackControllerV1.java
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java
  themepark-service/src/main/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/dto/request/ReqSlackPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/SlackFeignClientApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/service/SlackFeignClientServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/vo/TargetType.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/hashtags.http
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/waitings.http
Labels: ✨ feat

#241 🎈 test [#240 slack] Slack, SlackTemplate 테스트 코드 작성
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
  gateway-service/src/main/resources/application.yml
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slack/ReqSlackPostDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slackTemplate/ReqSlackTemplatePostDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/dto/request/slackTemplate/ReqSlackTemplatePutDTOApiV1.java
  slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackTemplateControllerApiV1.java
  slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackControllerApiV1Test.java
  slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackTemplateControllerApiV1Test.java
Labels: 🔨 refactor, 🎈 test

#243 🔨 refactor [#242-user] ResDTO Code 자료형 변경
  user-service/build.gradle
  user-service/src/main/java/com/business/userservice/presentation/controller/AuthControllerApiV1.java
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
Labels: 🔨 refactor

#244 ✨ feat [#223-waiting] 대기열 슬랙구현
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/SecurityConfig.java
  slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackControllerV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/dto/request/ReqSlackPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/SlackFeignClientApiV1.java
Labels: ✨ feat

#246 🔨 refactor [#245 slack] ResDTO Code 수정 및 내부 전용 api 경로 수정
  slack-service/build.gradle
  slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackControllerApiV1.java
  slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackEventTypeControllerApiV1.java
  slack-service/src/main/java/com/business/slackservice/presentation/controller/SlackTemplateControllerApiV1.java
  slack-service/src/test/java/com/business/slackservice/httpClient/slack.http
  slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackControllerApiV1Test.java
Labels: 🔨 refactor

#250 🎈 test [#249 slack] 성능 테스트용 yml 파일 생성
  slack-service/src/main/java/com/business/slackservice/application/service/RealSlackMessageSender.java
  slack-service/src/main/java/com/business/slackservice/application/service/SlackMessageSender.java
  slack-service/src/main/java/com/business/slackservice/application/service/SlackServiceImplApiV1.java
  slack-service/src/main/java/com/business/slackservice/application/service/mock/MockSlackMessageSender.java
  slack-service/src/main/resources/application-performance.yml
  slack-service/src/main/resources/application.yml
  slack-service/src/test/java/com/business/slackservice/httpClient/slack.http
Labels: 🔨 refactor, 🎈 test

#254 🔨 refactor[#251-waiting-lock] 대기열 동시성 리팩토링
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRepository.java
Labels: 🔨 refactor

#258 ✨ feat [#257 user] jwt 블랙리스트 구현
  user-service/build.gradle
  user-service/src/main/java/com/business/userservice/application/dto/request/ReqUserPutDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/dto/response/ResAuthPutDTOApiV1.java
  user-service/src/main/java/com/business/userservice/application/exception/AuthExceptionCode.java
  user-service/src/main/java/com/business/userservice/application/service/AuthServiceImplApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserServiceApiV1.java
  user-service/src/main/java/com/business/userservice/application/service/UserServiceImplApiV1.java
  user-service/src/main/java/com/business/userservice/domain/user/entity/RefreshTokenEntity.java
  user-service/src/main/java/com/business/userservice/domain/user/entity/UserEntity.java
  user-service/src/main/java/com/business/userservice/domain/user/repository/BlacklistRepository.java
  user-service/src/main/java/com/business/userservice/domain/user/repository/BlacklistRepositoryImpl.java
  user-service/src/main/java/com/business/userservice/domain/user/repository/RefreshTokenRepository.java
  user-service/src/main/java/com/business/userservice/domain/user/vo/JwtClaim.java
  user-service/src/main/java/com/business/userservice/domain/user/vo/TokenExpiration.java
  user-service/src/main/java/com/business/userservice/infrastructure/config/AuthSecurityConfig.java
  user-service/src/main/java/com/business/userservice/infrastructure/config/RedisConfig.java
  user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtAuthenticationFilter.java
  user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtProperties.java
  user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtUtil.java
  user-service/src/main/java/com/business/userservice/infrastructure/persistence/token/RefreshTokenJpaRepository.java
  user-service/src/main/java/com/business/userservice/infrastructure/security/UserDetailsImpl.java
  user-service/src/main/java/com/business/userservice/presentation/controller/UserControllerApiV1.java
Labels: ✨ feat

#260 ✨ feat [#259 gateway] 블랙리스트 확인
  gateway-service/build.gradle
  gateway-service/src/main/java/com/business/gatewayservice/application/exception/GatewayExceptionCode.java
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/RedisConfig.java
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/jwt/JwtTokenProvider.java
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/persistence/redis/BlacklistRepository.java
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/persistence/redis/BlacklistRepositoryImpl.java
Labels: ✨ feat

#262 ✨ feat [#261 slack] Slack EventType, Template Redis에 저장
  slack-service/build.gradle
  slack-service/src/main/java/com/business/slackservice/application/service/SlackServiceImplApiV1.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/config/RedisConfig.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackRedisRepository.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/persistence/SlackRedisRepositoryImpl.java
Labels: ✨ feat

#263 ✨ feat [#255-waiting-lock] 대기열 redis 분산락 캐싱 적용
  docker-compose.yml
  themepark-service/build.gradle
  themepark-service/src/main/java/com/business/themeparkservice/ThemeparkServiceApplication.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/dto/request/ReqWaitingPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/exception/WaitingExceptionCode.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/WaitingServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingRedisEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/repository/WaitingRedisRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/SlackFeignClientApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/dto/request/ReqSlackPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/service/SlackFeignClientServiceApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/feign/vo/TargetType.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/persistence/waiting/WaitingJpaRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/infastructure/redis/WaitingCrudRedisRepository.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV1.java
  themepark-service/src/main/resources/application-dev.yml
Labels: ✨ feat, 🔨 refactor

#267 ⚙ setting [#266-slack-user-gateway] Redis 설정
  gateway-service/src/main/resources/application.yml
  slack-service/src/main/resources/application-dev.yml
  user-service/src/main/resources/application-dev.yml
Labels: ⚙ setting

#268 ✨ feat [#256-stock-redis-lock] 재고 차감 시 Redis 활용한 분산 락 도입
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/application/exception/ProductExceptionCode.java
  product-service/src/main/java/com/business/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/config/RedissonConfig.java
  product-service/src/main/java/com/business/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/main/resources/application-dev.yml
  product-service/src/test/java/com/business/productservice/application/service/ProductServiceImplApiV1Test.java
Labels: ✨ feat, 🔨 refactor

#271 🐛 bug [#270-gateway-user-slack] Unable to connect to Redis 문제 해결
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/config/RedisConfig.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/config/RedisConfig.java
  user-service/src/main/java/com/business/userservice/infrastructure/config/RedisConfig.java
Labels: 🐛 bug

#275 ✏️ fix [#274-user] 토큰 만료 시간 계산 시 초에서 밀리초 단위 변환 누락 수정
  user-service/src/main/java/com/business/userservice/infrastructure/jwt/JwtUtil.java
Labels: ✏️ fix

#277 ⚙ setting [#276-slack] performance.yml에 redis 설정 추가
  slack-service/src/main/resources/application-performance.yml
Labels: ⚙ setting

#272 🔨 refactor [#269-product] 상품 서비스 v2 분리
  product-service/src/main/java/com/business/productservice/application/dto/v1/request/ReqProductPostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/v1/request/ReqProductPutDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/v1/request/ReqStockDecreasePostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/v1/request/ReqStockRestorePostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResProductGetDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResProductPostDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResProductPutDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/v1/response/ResStockGetByIdDTOApiV1.java
  product-service/src/main/java/com/business/productservice/application/dto/v2/request/ReqProductPostDTOApiV2.java
  product-service/src/main/java/com/business/productservice/application/dto/v2/request/ReqProductPutDTOApiV2.java
  product-service/src/main/java/com/business/productservice/application/dto/v2/request/ReqStockDecreasePostDTOApiV2.java
  product-service/src/main/java/com/business/productservice/application/dto/v2/request/ReqStockRestorePostDTOApiV2.java
  product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResProductGetByIdDTOApiV2.java
  product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResProductGetDTOApiV2.java
  product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResProductPostDTOApiV2.java
  product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResProductPutDTOApiV2.java
  product-service/src/main/java/com/business/productservice/application/dto/v2/response/ResStockGetByIdDTOApiV2.java
  product-service/src/main/java/com/business/productservice/application/service/v1/ProductServiceApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/v1/ProductServiceImplApiV1.java
  product-service/src/main/java/com/business/productservice/application/service/v2/ProductServiceApiV2.java
  product-service/src/main/java/com/business/productservice/application/service/v2/ProductServiceImplApiV2.java
  product-service/src/main/java/com/business/productservice/presentation/controller/v1/ProductControllerApiV1.java
  product-service/src/main/java/com/business/productservice/presentation/controller/v2/ProductControllerApiV2.java
  product-service/src/test/java/com/business/productservice/application/service/ProductServiceImplApiV1Test.java
  product-service/src/test/java/com/business/productservice/application/service/v1/ProductServiceImplApiV1Test.java
  product-service/src/test/java/com/business/productservice/application/service/v2/ProductServiceImplApiV2Test.java
  product-service/src/test/java/com/business/productservice/product/presentation/controller/ProductControllerApiV1Test.java
  product-service/src/test/resources/httpclient/productV2.http
Labels: 🔨 refactor

#280 ⚙ setting [#279 common] Prometheus와 Grafana를 이용한 모니터링
  docker-compose.yml
  eureka-server/build.gradle
  eureka-server/src/main/resources/application.yml
  gateway-service/build.gradle
  gateway-service/src/main/resources/application.yml
  prometheus.yml
  slack-service/build.gradle
  slack-service/src/main/resources/application-dev.yml
  slack-service/src/main/resources/application-performance.yml
  user-service/build.gradle
  user-service/src/main/resources/application-dev.yml
Labels: ⚙ setting

#282 ✨ feat [#273-stock-cache] 재고 차감 시 재고 정보에 대한 캐싱 구현
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
  gateway-service/src/main/resources/application.yml
  product-service/src/main/java/com/business/productservice/application/service/v2/ProductServiceImplApiV2.java
  product-service/src/main/java/com/business/productservice/config/RedissonConfig.java
  product-service/src/main/java/com/business/productservice/infrastructure/dto/ReqToSlackPostDTOApiV1.java
  product-service/src/test/java/com/business/productservice/application/service/v2/ProductServiceImplApiV2Test.java
Labels: ✨ feat

#286 ⚙ setting [#285-gateway] Resilience4J 설정
  gateway-service/build.gradle
  gateway-service/src/main/resources/application.yml
Labels: ⚙ setting

#287 ⚙ setting [#281-product-monitoring] prometheus, Grafana 모니터링 설정
  product-service/build.gradle
  product-service/src/main/resources/application-dev.yml
Labels: ⚙ setting

#290 ✨ feat [#278 zipkin] zipkin 기능 구현
  docker-compose.yml
  gateway-service/src/main/resources/application.yml
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/order/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/order/infrastructure/kafka/config/KafkaConfig.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/resources/application-dev.yml
Labels: ✨ feat

#297 🔨 refactor [#296-gateway] 라우팅 경로 수정
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
  gateway-service/src/main/resources/application.yml
Labels: 🔨 refactor

#300 ✏️ fix [#299-user] 블랙리스트 조회 메서드 반환 타입 수정
  user-service/src/main/java/com/business/userservice/application/service/AuthServiceImplApiV1.java
  user-service/src/main/java/com/business/userservice/domain/user/repository/BlacklistRepository.java
  user-service/src/main/java/com/business/userservice/domain/user/repository/BlacklistRepositoryImpl.java
Labels: ✏️ fix

#301 ✨ feat [#288-product-kafka] 상품 서비스 kafka 적용 (v3)
  product-service/build.gradle
  product-service/src/main/java/com/business/productservice/application/dto/v3/request/ReqProductPostDTOApiV3.java
  product-service/src/main/java/com/business/productservice/application/dto/v3/request/ReqProductPutDTOApiV3.java
  product-service/src/main/java/com/business/productservice/application/dto/v3/request/ReqStockDecreasePostDTOApiV3.java
  product-service/src/main/java/com/business/productservice/application/dto/v3/request/ReqStockRestorePostDTOApiV3.java
  product-service/src/main/java/com/business/productservice/application/dto/v3/response/ResProductGetByIdDTOApiV3.java
  product-service/src/main/java/com/business/productservice/application/dto/v3/response/ResProductGetDTOApiV3.java
  product-service/src/main/java/com/business/productservice/application/dto/v3/response/ResProductPostDTOApiV3.java
  product-service/src/main/java/com/business/productservice/application/dto/v3/response/ResProductPutDTOApiV3.java
  product-service/src/main/java/com/business/productservice/application/dto/v3/response/ResStockGetByIdDTOApiV3.java
  product-service/src/main/java/com/business/productservice/application/service/v3/ProductServiceApiV3.java
  product-service/src/main/java/com/business/productservice/application/service/v3/ProductServiceImplApiV3.java
  product-service/src/main/java/com/business/productservice/infrastructure/config/KafkaConfig.java
  product-service/src/main/java/com/business/productservice/infrastructure/config/RedissonConfig.java
  product-service/src/main/java/com/business/productservice/infrastructure/kafka/ProductKafkaConsumer.java
  product-service/src/main/java/com/business/productservice/infrastructure/kafka/SlackKafkaProducerService.java
  product-service/src/main/java/com/business/productservice/presentation/controller/v3/ProductControllerApiV3.java
  product-service/src/main/resources/application-dev.yml
Labels: ✨ feat

#302 ⚙ setting[#292-themepark] 테마파크 모니터링 설정
  docker-compose.yml
  themepark-service/build.gradle
  themepark-service/src/main/resources/application-dev.yml
Labels: ⚙ setting

#306 ✏️ fix [#304-slack] kafka 포트 번호 수정
  slack-service/src/main/resources/application-dev.yml
Labels: ✏️ fix

#298 🔨 refacto [/#293 order version] order 서비스 버전분리
  docker-compose.yml
  order-service/src/main/java/com/sparta/orderservice/order/application/dto/reponse/ResProductGetByIdDTOApi.java
  order-service/src/main/java/com/sparta/orderservice/order/application/facade/OrderFacade.java
  order-service/src/main/java/com/sparta/orderservice/order/application/facade/v1/OrderFacadeV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/facade/v2/OrderFacadeV2.java
  order-service/src/main/java/com/sparta/orderservice/order/application/facade/v3/OrderFacadeV3.java
  order-service/src/main/java/com/sparta/orderservice/order/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/order/application/service/v1/OrderServiceV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/service/v2/OrderServiceV2.java
  order-service/src/main/java/com/sparta/orderservice/order/application/service/v3/OrderServiceV3.java
  order-service/src/main/java/com/sparta/orderservice/order/application/usecase/v1/OrderUseCaseV1.java
  order-service/src/main/java/com/sparta/orderservice/order/application/usecase/v2/OrderUseCaseV2.java
  order-service/src/main/java/com/sparta/orderservice/order/application/usecase/v3/OrderUseCaseV3.java
  order-service/src/main/java/com/sparta/orderservice/order/domain/entity/OrderEntity.java
  order-service/src/main/java/com/sparta/orderservice/order/infrastructure/feign/ProductFeignClientApi.java
  order-service/src/main/java/com/sparta/orderservice/order/infrastructure/redis/config/RedisConfig.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/v1/OrderControllerApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/v2/OrderControllerApiV2.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/controller/v3/OrderControllerApiV3.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v1/request/ReqOrderPutDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v1/request/ReqOrdersPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v1/response/ResOrderGetDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v1/response/ResOrderPostDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v1/response/ResOrdersGetByIdDtoApiV1.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v2/request/ReqOrderPutDtoApiV2.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v2/request/ReqOrdersPostDtoApiV2.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v2/response/ResOrderGetDtoApiV2.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v2/response/ResOrderPostDtoApiV2.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v2/response/ResOrdersGetByIdDtoApiV2.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v3/request/ReqOrderPutDtoApiV3.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v3/request/ReqOrdersPostDtoApiV3.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v3/response/ResOrderGetDtoApiV3.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v3/response/ResOrderPostDtoApiV3.java
  order-service/src/main/java/com/sparta/orderservice/order/presentation/dto/v3/response/ResOrdersGetByIdDtoApiV3.java
  order-service/src/main/java/com/sparta/orderservice/payment/application/service/PaymentService.java
  order-service/src/test/java/com/sparta/orderservice/OrderServiceV1ApplicationTests.java
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/OrderControllerApiV1Test.java
  order-service/src/test/java/com/sparta/orderservice/presentation/controller/PaymentControllerApiV1Test.java
Labels: 🔨 refactor

#307 ✏️ fix[#303-themepark] 테마파크 코드 수정
  gateway-service/src/main/java/com/business/gatewayservice/infrastructure/filter/CustomPreFilter.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPostDTOApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/themepark/application/dto/request/ReqThemeparkPutDTOApiV1.java
  themepark-service/src/test/java/com/business/themeparkservice/httpclient/themeparks.http
Labels: ✏️ fix

#308 ✏️ fix [#303-themepark] 테마파크 코드 수정
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/v1/WaitingServiceImplApiV1.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/v2/WaitingServiceImplApiV2.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/application/service/v3/WaitingServiceImplApiV3.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/entity/WaitingEntity.java
  themepark-service/src/main/java/com/business/themeparkservice/waiting/domain/vo/WaitingStatus.java
  themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV3Test.java
Labels: ✏️ fix

#312 ⚙ setting[#309-themepark] 테마파크 zipkin 설정
  themepark-service/build.gradle
  themepark-service/src/main/resources/application-dev.yml
  themepark-service/src/test/java/com/business/themeparkservice/hashtag/presentation/controller/HashtagControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/themepark/presentation/controller/ThemeparkControllerApiV1Test.java
  themepark-service/src/test/java/com/business/themeparkservice/waiting/presentation/controller/WaitingControllerApiV3Test.java
Labels: ⚙ setting

#314 🎈 test [#313 user] 테스트 코드 수정
  user-service/src/test/java/com/business/userservice/user/presentation/controller/AuthControllerApiV1Test.java
  user-service/src/test/java/com/business/userservice/user/presentation/controller/UserControllerApiV1Test.java
Labels: 🎈 test

#316 🎈 test [#315-slack] v3으로 테스트 코드 수정
  slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackControllerApiV3Test.java
  slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackEventTypeControllerApiV3Test.java
  slack-service/src/test/java/com/business/slackservice/slack/presentation/controller/SlackTemplateControllerApiV3Test.java
Labels: ✨ feat

#317 ✨ feat [#310-product-restore-redis] 상품 재고 복구 레디스 분산락 적용 및 무제한 복구 처리 불가하도록 예외로직 추가
  product-service/src/main/java/com/business/productservice/application/exception/ProductExceptionCode.java
  product-service/src/main/java/com/business/productservice/application/service/v3/ProductServiceImplApiV3.java
  product-service/src/main/java/com/business/productservice/domain/product/entity/StockEntity.java
Labels: ✨ feat
