Repository numberOnethemepark/themepark, pull requests merged in 2025-05, with the labels that each got.

#330 🐛 bug [#328-product-restore] kafka 주문 서비스와의 타입 불일치 문제 해결
  product-service/src/main/java/com/business/productservice/application/service/v3/ProductServiceImplApiV3.java
  product-service/src/main/java/com/business/productservice/infrastructure/config/KafkaConfig.java
  product-service/src/main/java/com/business/productservice/infrastructure/kafka/ProductKafkaConsumer.java
  product-service/src/main/java/com/business/productservice/infrastructure/kafka/TestKafkaProducer.java
  product-service/src/main/java/com/business/productservice/presentation/controller/v3/ProductControllerApiV3.java
Labels: 🐛 bug

#332 localhost > ip 주소 수정
  product-service/src/main/java/com/business/productservice/infrastructure/config/KafkaConfig.java
  slack-service/src/main/java/com/business/slackservice/infrastructure/config/ConsumerApplicationKafkaConfig.java
Labels: ✏️ fix

#333 🔨 refactor kafka host주소 변경
  themepark-service/src/main/java/com/business/themeparkservice/waiting/config/KafkaConfig.java
Labels: 🔨 refactor

#336 ⚙ setting [#335-gateway] yml 파일 분리 및 common 버전 업
  gateway-service/build.gradle
  gateway-service/src/main/resources/application-prod.yml
  gateway-service/src/main/resources/application.yml
Labels: ⚙ setting

#338 🐛 bug [#337-gateway] TimeLimiter 기본 timeoutDuration을 6초로 연장
  gateway-service/src/main/resources/application-prod.yml
Labels: 🐛 bug

#340 🐛 bug [#339 gateway slack] timeoutDuration, @Profile 설정 변경
  gateway-service/src/main/resources/application-prod.yml
  slack-service/src/main/java/com/business/slackservice/application/service/RealSlackMessageSender.java
Labels: 🐛 bug

#342 ✏️ fix [#341-eureka-docker] Docker 환경에서 Eureka 등록 주소 수정 및 dockerfile 생성
  docker-compose.yml
  eureka-server/Dockerfile
  eureka-server/src/main/resources/application.yml
Labels: ✏️ fix

#344 Update README.md
  README.md
Labels: 📄 docs

#345 📄 docs [readme] readme 수정
  README.md
Labels: 📄 docs
